[package]
name = "fuse-async"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.10.0"
libc = "0.2.178"
tokio = { version = "1.48.0", features = ["fs"] }
zerocopy = { version = "0.8.31", features = ["derive"] }
